# Gitpod configuration
image:
  file: Dockerfile.vnc

ports:
  - port: 6080
    onOpen: open-preview
    visibility: public
    description: noVNC Browser View

tasks:
  - name: Start Scraper with VNC
    init: |
      echo "Setting up environment..."
      npm install
    command: |
      echo "✅ VNC Password: password"
      echo "✅ Browser view available at port 6080"
      echo "Starting services..."
      /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

vscode:
  extensions:
    - ms-vscode.js-debug