name = "nse-pre-open-api"
main = "src/api/worker.ts"
compatibility_date = "2024-09-24"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "nse-pre-open-api"
route = { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }

# R2 bucket binding - automatically connects to your R2 bucket
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pre-open-market"

# Durable Objects binding for rate limiter
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "nse-pre-open-api"

# Durable Object migration
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]